import type { DB } from "./types";

// 初始种子数据：安省中小型肉企（Tier 2/3）+ 七三开渠道商
// 部署后可由 /api/recruitment/scan 与 /api/pipeline/run 自动扩展

const now = new Date().toISOString();

export const seedDB: DB = {
  leads: [
    {
      id: "L-001",
      company: "Golden Pack Meats",
      city: "Mississauga",
      region: "安省",
      tier: "Tier2",
      employees: 220,
      lat: 43.589,
      lon: -79.6441,
      plantManager: { name: "Dave Caron", title: "Plant Manager", email: "dcaron@goldenpack.ca" },
      productInterest: "AK201000",
      stage: "locked",
      priority: "A",
      source: "招聘监控",
      wagePerHour: 23,
      notes: "后道装袋工序高度依赖人工，缺工红灯。",
      createdAt: now,
      updatedAt: now,
      recruitmentSignalId: "S-001",
    },
    {
      id: "L-002",
      company: "Ontario Prime Proteins",
      city: "Toronto",
      region: "安省",
      tier: "Tier3",
      employees: 95,
      lat: 43.6532,
      lon: -79.3832,
      plantManager: { name: "Maria Lopez", title: "Plant Manager", email: "mlopez@ontarioprime.ca" },
      productInterest: "AK0200",
      stage: "scraped",
      priority: "B",
      source: "全网爬取",
      wagePerHour: 22,
      notes: "小型精细分割厂，关注合规。",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "L-003",
      company: "Grand River Meat Co.",
      city: "Guelph",
      region: "安省",
      tier: "Tier2",
      employees: 180,
      lat: 43.5448,
      lon: -80.2482,
      plantManager: { name: "Tom Becker", title: "Operations Manager", email: "tbecker@grandriver.ca" },
      productInterest: "AK-Line",
      stage: "locked",
      priority: "A",
      source: "招聘监控",
      wagePerHour: 23.5,
      notes: "整线升级意向，缺工信号明显。",
      createdAt: now,
      updatedAt: now,
      recruitmentSignalId: "S-002",
    },
    {
      id: "L-004",
      company: "Thames Valley Foods",
      city: "London",
      region: "安省",
      tier: "Tier3",
      employees: 110,
      lat: 42.9849,
      lon: -81.2453,
      plantManager: { name: "Sarah Wu", title: "Plant Manager", email: "swu@thamesvalley.ca" },
      productInterest: "AK201000",
      stage: "scraped",
      priority: "B",
      source: "全网爬取",
      wagePerHour: 21.5,
      notes: "",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "L-005",
      company: "Hamilton Butcher Supply",
      city: "Hamilton",
      region: "安省",
      tier: "Tier2",
      employees: 160,
      lat: 43.2557,
      lon: -79.8711,
      plantManager: { name: "Greg Pace", title: "Plant Manager", email: "gpace@hamiltonbutcher.ca" },
      productInterest: "AK0200",
      stage: "outreach",
      priority: "B",
      source: "展会",
      wagePerHour: 22.5,
      notes: "已发送首封冷邮件，等待回复。",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "L-006",
      company: "Waterloo Fresh Cuts",
      city: "Kitchener",
      region: "安省",
      tier: "Tier3",
      employees: 85,
      lat: 43.4516,
      lon: -80.4925,
      plantManager: { name: "Emily Tran", title: "Plant Manager", email: "etran@waterloofresh.ca" },
      productInterest: "AK201000",
      stage: "locked",
      priority: "A",
      source: "招聘监控",
      wagePerHour: 23,
      notes: "装袋线缺工，密集招聘 Packer。",
      createdAt: now,
      updatedAt: now,
      recruitmentSignalId: "S-003",
    },
    {
      id: "L-007",
      company: "Brampton Protein Packers",
      city: "Brampton",
      region: "安省",
      tier: "Tier2",
      employees: 200,
      lat: 43.7315,
      lon: -79.7624,
      plantManager: { name: "Raj Singh", title: "Plant Manager", email: "rsingh@bramptonprotein.ca" },
      productInterest: "AK-Line",
      stage: "scraped",
      priority: "C",
      source: "全网爬取",
      wagePerHour: 23,
      notes: "",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "L-008",
      company: "Windsor Meat Works",
      city: "Windsor",
      region: "安省",
      tier: "Tier3",
      employees: 90,
      lat: 42.3149,
      lon: -83.0364,
      plantManager: { name: "Paul Moreau", title: "Plant Manager", email: "pmoreau@windsormeat.ca" },
      productInterest: "AK0200",
      stage: "scraped",
      priority: "C",
      source: "全网爬取",
      wagePerHour: 21,
      notes: "",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "L-009",
      company: "Niagara Meat Processors",
      city: "St. Catharines",
      region: "安省",
      tier: "Tier2",
      employees: 150,
      lat: 43.1594,
      lon: -79.2469,
      plantManager: { name: "Laura Fontaine", title: "Plant Manager", email: "lfontaine@niagaramt.ca" },
      productInterest: "AK201000",
      stage: "locked",
      priority: "A",
      source: "招聘监控",
      wagePerHour: 22.5,
      notes: "装袋产能瓶颈，缺工红灯。",
      createdAt: now,
      updatedAt: now,
      recruitmentSignalId: "S-004",
    },
    {
      id: "L-010",
      company: "Belleville Beef Co.",
      city: "Belleville",
      region: "安省",
      tier: "Tier3",
      employees: 70,
      lat: 44.1642,
      lon: -77.3873,
      plantManager: { name: "Ken Adams", title: "Plant Manager", email: "kadams@bellevillebeef.ca" },
      productInterest: "AK0200",
      stage: "scraped",
      priority: "C",
      source: "全网爬取",
      wagePerHour: 21,
      notes: "",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "L-011",
      company: "Stratford Sausage House",
      city: "Stratford",
      region: "安省",
      tier: "Tier3",
      employees: 60,
      lat: 43.3733,
      lon: -80.9821,
      plantManager: { name: "Nina Roth", title: "Plant Manager", email: "nroth@stratfordsausage.ca" },
      productInterest: "AK0200",
      stage: "scraped",
      priority: "C",
      source: "全网爬取",
      wagePerHour: 22,
      notes: "",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "L-012",
      company: "Northern Quality Meats",
      city: "Sudbury",
      region: "安省",
      tier: "Tier3",
      employees: 80,
      lat: 46.4817,
      lon: -80.9916,
      plantManager: { name: "Olivier Tremblay", title: "Plant Manager", email: "otremblay@northernquality.ca" },
      productInterest: "AK201000",
      stage: "scraped",
      priority: "C",
      source: "全网爬取",
      wagePerHour: 22,
      notes: "",
      createdAt: now,
      updatedAt: now,
    },
  ],
  signals: [
    {
      id: "S-001",
      leadId: "L-001",
      company: "Golden Pack Meats",
      city: "Mississauga",
      roles: [
        { role: "Packaging Line Operator", count: 14, wagePerHour: 23 },
        { role: "Packer", count: 9, wagePerHour: 22.5 },
        { role: "Maintenance Technician", count: 2 },
      ],
      severity: "red",
      priority: "A",
      detectedAt: now,
      note: "30 天内密集招聘 23 个装袋/包装岗 → 后道极度缺工，开发优先级 A。",
    },
    {
      id: "S-002",
      leadId: "L-003",
      company: "Grand River Meat Co.",
      city: "Guelph",
      roles: [
        { role: "Production Supervisor", count: 3, wagePerHour: 28 },
        { role: "Packaging Line Operator", count: 11, wagePerHour: 23.5 },
      ],
      severity: "red",
      priority: "A",
      detectedAt: now,
      note: "装袋线 11 岗空缺 + 主管扩编 → 产能扩张信号，优先级 A。",
    },
    {
      id: "S-003",
      leadId: "L-006",
      company: "Waterloo Fresh Cuts",
      city: "Kitchener",
      roles: [{ role: "Packer", count: 12, wagePerHour: 23 }],
      severity: "red",
      priority: "A",
      detectedAt: now,
      note: "单岗 Packer 招聘 12 人 → 装袋工序满负荷，缺工红灯。",
    },
    {
      id: "S-004",
      leadId: "L-009",
      company: "Niagara Meat Processors",
      city: "St. Catharines",
      roles: [
        { role: "Packaging Line Operator", count: 8, wagePerHour: 22.5 },
        { role: "Packer", count: 6, wagePerHour: 22 },
      ],
      severity: "red",
      priority: "A",
      detectedAt: now,
      note: "装袋相关 14 岗空缺 → 后道瓶颈，优先级 A。",
    },
  ],
  emails: [],
  visits: [],
  partners: [
    {
      id: "P-01",
      name: "GTA Integration Systems",
      type: "SI",
      city: "Mississauga",
      lat: 43.589,
      lon: -79.6441,
      commissionSplit: "七三开 · 渠道商拿综合毛利 70%",
      phone: "+1 905-555-0101",
      email: "sales@gtasys.ca",
    },
    {
      id: "P-02",
      name: "Toronto Food Automation",
      type: "代理",
      city: "Toronto",
      lat: 43.6532,
      lon: -79.3832,
      commissionSplit: "七三开 · 渠道商拿综合毛利 70%",
      phone: "+1 416-555-0102",
      email: "info@torontofood.ca",
    },
    {
      id: "P-03",
      name: "Guelph MES Partners",
      type: "MES",
      city: "Guelph",
      lat: 43.5448,
      lon: -80.2482,
      commissionSplit: "七三开 · 渠道商拿综合毛利 70%",
      phone: "+1 519-555-0103",
      email: "contact@guelphmes.ca",
    },
    {
      id: "P-04",
      name: "London Packaging Solutions",
      type: "代理",
      city: "London",
      lat: 42.9849,
      lon: -81.2453,
      commissionSplit: "七三开 · 渠道商拿综合毛利 70%",
      phone: "+1 519-555-0104",
      email: "sales@londonpack.ca",
    },
    {
      id: "P-05",
      name: "Hamilton Line Engineering",
      type: "SI",
      city: "Hamilton",
      lat: 43.2557,
      lon: -79.8711,
      commissionSplit: "七三开 · 渠道商拿综合毛利 70%",
      phone: "+1 905-555-0105",
      email: "eng@hamiltonline.ca",
    },
    {
      id: "P-06",
      name: "Kitchener Automation Group",
      type: "代理",
      city: "Kitchener",
      lat: 43.4516,
      lon: -80.4925,
      commissionSplit: "七三开 · 渠道商拿综合毛利 70%",
      phone: "+1 519-555-0106",
      email: "hello@kitchenerauto.ca",
    },
  ],
  activities: [
    {
      id: "A-001",
      at: now,
      type: "system",
      message: "系统初始化：载入 12 家安省肉企线索与 6 家七三开渠道商。",
    },
  ],
};
